export default [
  {
    imageSrc: 'materialTableLogo',
    imageAlt: 'Material-Table logo',
    name: 'material-table',
    path: '/technologies/material-table',
    id: 'material-table',
    routes: [
      {
        imageSrc: '',
        imageAlt: '',
        name: 'Marvel Characters',
        path: '/technologies/material-table/characters',
        id: 'material-table-characters',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
    ],
  },
  {
    imageSrc: 'tubularReactLogo',
    imageAlt: 'Tubular-React logo',
    name: 'Tubular-React',
    path: '/technologies/tubular-react',
    id: 'tubular-react',
    routes: [
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
      {
        imageSrc: '',
        imageAlt: '',
        name: '',
        path: '',
        id: '',
      },
    ],
  },
];
